@hostname = localhost
@port = 5001
@host = {{hostname}}:{{port}}
@admintoken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImU5YTY0ODdmLTczY2QtNDBjNS05MzkzLWQ3ZWY4NDRhMWEyZiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJUZXN0QWRtaW4iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTczOTUzODkzNSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEifQ.MM3QzC4AxX3pgIv3bT5i2bciqcrPUjHxfFzohNJ4Uvw
@filmstudiotoken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjdjNWNiZmJjLThlYzYtNGM1MS1iOWIwLWQ1ZDUxNmI4MzdjMyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJUZXN0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiZmlsbXN0dWRpbyIsImV4cCI6MTczOTU0NDUzNiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEifQ.Y_wSgFPeNN-3rs6JQs6xOnlZOiEY_Qyuth-aR9UWnv0
@filmstudioid= 7c5cbfbc-8ec6-4c51-b9b0-d5d516b837c3
###

//SKAPA USER-ADMIN
POST http://{{host}}/api/users/register
Content-Type: application/json

{
  "username": "TestAdmin",
  "password": "Test123!",
  "isAdmin": true
}

###

// SKAPA FILMSTUDIO
POST http://{{host}}/api/filmstudio/register
Content-Type: application/json

{
  "username": "Test",
  "filmStudioName":"Test Studio",
  "city":"Stockholm",
  "password": "Test123!"
}

###

//AUTENTISERING
POST http://{{host}}/api/users/authenticate
Content-Type: application/json

{
    "username": "Test",
    "password": "Test123!"
} 

###

//LÄGG TILL NY FILM ENDAST FÖR AUTENTISERAD ADMIN ANNARS 403 FORBIDDEN
POST http://{{host}}/api/films
Authorization: Bearer {{admintoken}}
Content-Type: application/json

{
     "title":"Gone with the wind",
    "director":"Victor Fleming",
    "releaseYear":1939,
    "genre":"Romantik",
    "numberOfCopies":1
}

###

//HÄMTA ALLA FILMSTUDIOS--Ett lyckat anrop med en oautentiserad användare eller en autentiserad filmstudio ska ge tillbaka ett json-objekt som INTE innehåller listan RentedFilmCopies eller egenskapen City.
GET http://{{host}}/api/filmstudios
Authorization: Bearer {{admintoken}}

###

//HÄMTA EN SPECIFIK FILMSTUDIO--Ett lyckat anrop med en oautentiserad användare eller en autentiserad filmstudio men som inte är filmstudion som eftersöks ska ge tillbaka ett json-objekt som NTE innehåller listan RentedFilmCopies eller egenskapen City. Om admin eller en autentiserad filmstudio med samma id som eftersöks ska returnera full objekt.
GET http://{{host}}/api/filmstudio/{{filmstudioid}}
Authorization: Bearer {{filmstudiotoken}}

###

//HÄMTA ALLA FILMER-- autentiserad användare (filmstudio eller admin) ska få tillbaka en array med objekt som uppfyller interface:et IFilm, annars returneras samma men utan egenskapen "FilmCopies"
GET http://{{host}}/api/films
Authorization: Bearer {{filmstudiotoken}}

###

//HÄMTA EN SPECIFIK FILM-- autentiserad användare (filmstudio eller admin) ska få tillbaka objekt som uppfyller interface:et IFilm, annars returneras samma men utan egenskapen "FilmCopies"
GET http://{{host}}/api/films/1
Authorization: Bearer {{filmstudiotoken}}

###

//ÄNDRA INFORMATIONEN OM EN FILM-- en autentiserad admin ska få det uppdaterade objektet som är ett json-objekt som uppfyller interface:et IFilm. Ett anrop av en icke-autentiserad användare ska ge statuskod 401.
PATCH http://{{host}}/api/films/20
Authorization: Bearer {{admintoken}}
Content-Type: application/json

{
    "title":"The Silence of the Lambs",
    "director":"Victor Fleming",
    "releaseYear":1939,
    "genre":"Romantik",
    "numberOfCopies":0
}

###

//LÅNA ETT EXEMPLAR AV EN FILM-- Endast för autentiserad filmstudio annars 401, om filmen redan är lånad av samma studio 403, om filmen eller ledig exemplar inte finns 409
POST http://{{host}}/api/films/rent?id=18&studioid={{filmstudioid}}
Authorization: Bearer {{filmstudiotoken}}

###

//LÄMNA TILLBAKA ETT LÅNAT EXEMPLAR AV EN FILM-- Endast för autentiserad filmstudio annars 401, om filmen inte finns 409
POST http://{{host}}/api/films/return?id=4&studioid={{filmstudioid}}
Authorization: Bearer {{filmstudiotoken}}

###

//HÄMTA DE LÅNADE FILMER FÖR DEN AUTENTISERADE STUDION-- ska fåtillbaka en array med objekt som motsvarar IFilmCopy, om ej autentiserad 401
GET http://{{host}}/api/mystudio/rentals
Authorization: Bearer {{filmstudiotoken}}